cast-api:
  base-url: http://cast-api:8080/
management:
  endpoints:
    web:
      exposure:
        include: health, mappings
spring:
  data:
    rest:
      base-path: api/v1
  datasource:
    url: jdbc:mysql://movies-db:3306/movies
    username: movies
    password: fEvfvJz8mKfjkV943JTA
  jpa:
    open-in-view: false
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

---

cast-api:
  base-url: http://localhost:5013
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3308/movies